rails/shuffle/config/routes.rb
Rails.application.routes.draw do
  resources :members

  root 'application#index'
  get 'shuffle/peek' => 'application#peek'
  post 'shuffle/cycle' => 'application#cycle'
  get 'shuffle/random' => 'application#random'

end

rails/shuffle/app/models/member.rb
class Member < ActiveRecord::Base
  validates :name, :initials, :presence => true

end

rails/shuffle/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout 'application'

  def index

    if params[:next_member] == nil
      @next_member = peek
    else
      @next_member = params[:next_member]
    end
    if params[:random_member] == nil
      @random_member = get_random
    else
      @random_member = params[:random_member]
    end

    render :shuffle
  end

  def cycle
    @next_member = take_turn
    @random_member = get_random
    render :shuffle
  end

  def random
    @next_member = peek
    @random_member = get_random
    render :shuffle
  end

  private
    def peek
      puts "Peek called"
      # TODO
      return Member.all[0]
    end

    def take_turn
      puts "Take turn called"
      # TODO
      return Member.all[0]
    end

    def get_random
      puts "Get random called"
      # TODO
      return Member.all[0]
    end
end

rails/shuffle/app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        flash[:success] = 'Member was successfully created.'
        format.html { redirect_to members_url }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        flash[:success] = 'Member was successfully updated.'
        format.html { redirect_to members_url }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      flash[:success] = 'Member was successfully destroyed.'
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :initials)
    end
end

rails/shuffle/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/shuffle/app/helpers/members_helper.rb
module MembersHelper
end

rails/shuffle/app/views/application/shuffle.html.erb
<div class="row">
  <div class="col-sm-6">

    <%= button_to "Shuffle", shuffle_cycle_path, :class => "btn btn-primary", :method => 'post' %>
    <%= @next_member.initials + " " + @next_member.name %>

  </div>
  <div class="col-sm-6">

    <%= button_to "Random", shuffle_random_path, :class => "btn btn-primary", :method => 'get' %>
    <%= @random_member.initials + " " + @random_member.name %>

  </div>
</div>

rails/shuffle/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shuffle</title>
  <%= render 'layouts/includes/header' %>
</head>
<body>

<%= render 'layouts/includes/navbar' %>

<div class="container">
  <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>"><%= msg %></div>
  <% end %>
  <%= yield %>
</div>

<div id="footer">
  <%= render 'layouts/includes/footer' %>
</div>

</body>
</html>

rails/shuffle/app/views/layouts/includes/_footer.erb
<!-- Footer -->
<footer>
  <div class="row">
    <div class="col-lg-12 text-center">
      <p>Copyright &copy; Noptech <%= Date.today.year %></p>
    </div>
  </div>
</footer>

<%= javascript_include_tag "application" %>

rails/shuffle/app/views/layouts/includes/_header.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

rails/shuffle/app/views/layouts/includes/_navbar.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Shuffle', root_path, :class => "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to 'Manage members', members_path %>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

rails/shuffle/app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :initials %><br>
    <%= f.text_field :initials %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/shuffle/app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

rails/shuffle/app/views/members/index.html.erb
<h1>Listing members</h1>
<div class="row">
  <div class="col-sm-12">

    <table class="table table-striped">
      <thead>
      <tr>
        <th>Name</th>
        <th>Initials</th>
        <th colspan="2"></th>
      </tr>
      </thead>

      <tbody>
      <% @members.each do |member| %>
          <tr>
            <td><%= member.name %></td>
            <td><%= member.initials %></td>
            <td><%= link_to 'Edit', edit_member_path(member) %></td>
            <td><%= link_to 'Destroy', member, method: :delete, data: {confirm: 'Are you sure?'} %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <br/>

    <%= button_to 'New Member', new_member_path, :class => "btn btn-primary pull-right", :method => "get" %>
  </div>
</div>

rails/shuffle/app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>